---
# tasks file for nginx
- name: Install package
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Create folder sites
  ansible.builtin.file:
    path: /var/www/sites
    mode: '0755'
    owner: www-data
    group: www-data
    state: directory
  notify: Restart nginx